### ISSUE TITLE
如何解码txs数据

### ISSUE THREAD

**Issue by singpenguin** [sammchardy/python-binance-chain#10]
请问如何进行解码txs数据，获取完块数据后，交易数据是编码过的，没有找到解码方法。

'data': {'txs': ['xwHwYl3uCk4qLIf6CiMKFI6nDX0uqKFLorM9GNXfvW+uCm6oEgsKA0JOQhCCzc/zGBIjChSRk3Ug9ARY9bQU0meWG0bBl4ndcBILCgNCTkIQgs3P8xgSbwom61rphyECY27UXl6gX6oOXbLxltBEgO2x6zsGPFXz0d+AgMFWU7YSQFPEqcBxlWj3u96l92HKZBzIMZJCFpHf0SOUW39s0dkHeZtKjODyL3lspQHf7EwpZtEPdv8+eq7OncifaKICMnsYMiDQGiAC']}

非常感谢了。

**Comment by summerxue1992** [comment]
@singpenguin    你也在用这个库嘛？请教一下，为什么我用HttpApiClient中getaccount方法时，总是失败，提示连接不到默认的api服务，正式网测试网都不行。加下微信或电报哈，15501199287。
Are you using this library?I would like to ask you why I always fail to use getaccount method in HttpApiClient, indicating that the default API service cannot be connected, and the official network test network is not available.

**Comment by singpenguin** [comment]
@summerxue1992 我没用这个库，只是看到了，上面txs的解码方法已经知道了，我是自己写的库连接节点。这个库可以正常连接，什么都不用配置。
