### ISSUE TITLE
TypeError: broadcast_msg() missing 1 required positional argument: 'msg'

### ISSUE THREAD

**Issue by mantle3576** [sammchardy/python-binance-chain#20]
res = client.broadcast_msg(transfer_msg, sync=True)
TypeError: broadcast_msg() missing 1 required positional argument: 'msg'

Any idea how to fix this error?

from binance_chain.http import HttpApiClient
from binance_chain.messages import TransferMsg
from binance_chain.wallet import Wallet
from binance_chain.environment import BinanceEnvironment

env = BinanceEnvironment.get_production_env()
wallet = Wallet('my private key')
client = HttpApiClient

transfer_msg = TransferMsg(
    wallet=wallet,
    symbol='BNB',
    amount=1,
    to_address='address',
)
res = client.broadcast_msg(transfer_msg, sync=True)

**Comment by sammchardy** [comment]
Hi @mantle3576 make sure you either name all parameters in the function call, or don't name them.

try
```
res = client.broadcast_msg(msg=transfer_msg, sync=True)
```

**Comment by mantle3576** [comment]
Thanks for your labor :)

**Comment by diliosuhor** [comment]
thank you! @sammchardy
