### ISSUE TITLE
Conflicting dependencies issue

### ISSUE THREAD

**Issue by cheeseandcereal** [sammchardy/python-binance-chain#29]
This package requires the pip package `pywallet`, which in turn requires a package called `two1`.

This package has a very strict (and not to mention, unnecessary) set of requirement dependencies (see: https://github.com/21dotco/two1-python/blob/master/setup.py#L13) which causes dependency conflicts when installing this python-binance-chain package.

Considering that pywallet is literally only used to get a private key out of a seed via BIP32 standards, I would recommend using a lighter dependency, or at least a dependency that doesn't result in conflicts.

If you would agree @sammchardy (or anyone else who maintains this repository), I could probably put together a PR for this, I just don't want to do the work before I know you'd be willing to accept this change. Please let me know.

**Comment by sammchardy** [comment]
Hi @cheeseandcereal always happy to reduce dependency weight if you are able to.

**Comment by cheeseandcereal** [comment]
@sammchardy Implemented with pycoin instead.

If possible, it would be awesome if a release could be made after merging with these changes.

**Comment by lobatt** [comment]
Thanks @cheeseandcereal !
I had the same issue when trying to install this library. 

@sammchardy it would be great if we can do a release since `pip install python-binance-chain`  does not work right now.
