### ISSUE TITLE
Unable to import HttpApiSigningClient

### ISSUE THREAD

**Issue by nandubatchu** [sammchardy/python-binance-chain#3]
@sammchardy 
Unable to find the module `signing` under the pypi package python-binance-chain:
```from binance_chain.signing.http import HttpApiSigningClient```

**Comment by sammchardy** [comment]
Yes, you would be correct, the module was missing an __init__.py and not being included in the package.

Try v0.1.5

**Comment by nandubatchu** [comment]
@sammchardy cool. Thank you again for quick response. Can I use the `bnbcli api-server client` as the local signing client? I don't see any options there to enable username and password on the server.

**Comment by sammchardy** [comment]
For your local node I think you need to use the node_rpc client instead. at `binance_chain.node_rpc.http`, there are sync and async clients there.

The signing client is to communicate with my submission for the signing service competition https://github.com/sammchardy/binance-chain-signing-service. It's a standalone server you run with your private key and can sign requests through it, possibly giving others access with username and password.

**Comment by nandubatchu** [comment]
@sammchardy can the offline-signing steps be implemented with the help of `binance_chain.node_rpc.http` lightnode clients?

**Comment by sammchardy** [comment]
I'm not 100% sure what you're asking.

You can broadcast messages through the Node RPC client.

I have an example on the docs here https://github.com/sammchardy/python-binance-chain#broadcast-messages-on-node-rpc-http-client

I'm on Telegram if you want to chat there, may be easier.

**Comment by nandubatchu** [comment]
@sammchardy the import for HttpRpcClient is not working.
I guess there is a module called `node_rpc` along with the `node_rpc.py` file. Is this intentional?

**Comment by sammchardy** [comment]
Hmm, a build directory was keeping the old file. Try v0.1.7

**Comment by nandubatchu** [comment]
is v0.1.7 released on pypi?

**Comment by nandubatchu** [comment]
@sammchardy also I see there is a missing information of txFee in the HttpApiClient().get_transaction() response.

**Comment by nandubatchu** [comment]
@sammchardy any update on the missing txFee field?

**Comment by sammchardy** [comment]
@nandubatchu in regard to `txFee`, the library doesn't remove in information. If something is missing then it may be an issue with Binance Chain itself.

**Comment by nandubatchu** [comment]
@sammchardy how do I get the Fee incurred for a particular transaction hash? Is there any method to fetch the tx_receipt like bitcoin?

**Comment by sammchardy** [comment]
`client.get_transactions(address=<your_address>)` shows the fee.
According to `client.get_fees()`, there is no fee for new orders.

I would have expected `client.get_transaction(<tx_hash>)` to show the fee but it doesn't. 

May be worth following up with Binance Dex about the responses here.

**Comment by nandubatchu** [comment]
@sammchardy are you following up with the Binance Dex? Can you share the link to the follow up request?

**Comment by sammchardy** [comment]
Hi @nandubatchu I tried commenting on the Telegram group but got no response. It may be worth following up yourself with this.
