### ISSUE TITLE
Missing option to provide 'memo' in HttpRpcClient().broadcast_msg

### ISSUE THREAD

**Issue by nandubatchu** [sammchardy/python-binance-chain#4]
@sammchardy While broadcasting TransferMsg via HttpRpcClient, unable to provide 'memo' field.

**Comment by nandubatchu** [comment]
@sammchardy Can we wrap TransferMsg into StdMsg while broadcasting via the node_rpc client?

**Comment by sammchardy** [comment]
The function already wraps it properly to send as a signed message. 

In the develop branch I've included an option to pass a memo parameter for the transfer message. I will package it properly later, but you can pop install the develop branch to try.

**Comment by sammchardy** [comment]
@nandubatchu I've included the `memo` parameter in v0.1.8

**Comment by nandubatchu** [comment]
@sammchardy cool. working fine for me.
